<a href="https://colab.research.google.com/github/arda-aslan6028/Arda-Aslan-Stat112-Project/blob/main/EPL_cleaned_dataset_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#importing necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd


pd.set_option('display.max_columns', None) #displaying all columns



df = pd.read_csv('PremierLeague.csv',index_col=0) #reading the dataset and first observations
print(df.head())
df=pd.read_csv('PremierLeague.csv')
df.head()

                                       Season  MatchWeek        Date Time  \
MatchID
1993-1994_Arsenal_Coventry          1993-1994          1  1993-08-14  NaN
1993-1994_Aston Villa_QPR           1993-1994          1  1993-08-14  NaN
1993-1994_Chelsea_Blackburn         1993-1994          1  1993-08-14  NaN
1993-1994_Liverpool_Sheffield Weds  1993-1994          1  1993-08-14  NaN
1993-1994_Man City_Leeds            1993-1994          1  1993-08-14  NaN

                                       HomeTeam        AwayTeam  \
MatchID
1993-1994_Arsenal_Coventry              Arsenal        Coventry
1993-1994_Aston Villa_QPR           Aston Villa             QPR
1993-1994_Chelsea_Blackburn             Chelsea       Blackburn
1993-1994_Liverpool_Sheffield Weds    Liverpool  Sheffield Weds
1993-1994_Man City_Leeds               Man City           Leeds

                                    FullTimeHomeTeamGoals  \
MatchID
1993-1994_Arsenal_Coventry                              0
1993-1994_Aston Villa_QPR                               4
1993-1994_Chelsea_Blackburn                             1
1993-1994_Liverpool_Sheffield Weds                      2
1993-1994_Man City_Leeds                                1

                                    FullTimeAwayTeamGoals FullTimeResult  \
MatchID
1993-1994_Arsenal_Coventry                              3              A
1993-1994_Aston Villa_QPR                               1              H
1993-1994_Chelsea_Blackburn                             2              A
1993-1994_Liverpool_Sheffield Weds                      0              H
1993-1994_Man City_Leeds                                1              D

                                    HalfTimeHomeTeamGoals  \
MatchID
1993-1994_Arsenal_Coventry                            NaN
1993-1994_Aston Villa_QPR                             NaN
1993-1994_Chelsea_Blackburn                           NaN
1993-1994_Liverpool_Sheffield Weds                    NaN
1993-1994_Man City_Leeds                              NaN

                                    HalfTimeAwayTeamGoals HalfTimeResult  \
MatchID
1993-1994_Arsenal_Coventry                            NaN            NaN
1993-1994_Aston Villa_QPR                             NaN            NaN
1993-1994_Chelsea_Blackburn                           NaN            NaN
1993-1994_Liverpool_Sheffield Weds                    NaN            NaN
1993-1994_Man City_Leeds                              NaN            NaN

                                   Referee  HomeTeamShots  AwayTeamShots  \
MatchID
1993-1994_Arsenal_Coventry             NaN            NaN            NaN
1993-1994_Aston Villa_QPR              NaN            NaN            NaN
1993-1994_Chelsea_Blackburn            NaN            NaN            NaN
1993-1994_Liverpool_Sheffield Weds     NaN            NaN            NaN
1993-1994_Man City_Leeds               NaN            NaN            NaN

                                    HomeTeamShotsOnTarget  \
MatchID
1993-1994_Arsenal_Coventry                            NaN
1993-1994_Aston Villa_QPR                             NaN
1993-1994_Chelsea_Blackburn                           NaN
1993-1994_Liverpool_Sheffield Weds                    NaN
1993-1994_Man City_Leeds                              NaN

                                    AwayTeamShotsOnTarget  HomeTeamCorners  \
MatchID
1993-1994_Arsenal_Coventry                            NaN              NaN
1993-1994_Aston Villa_QPR                             NaN              NaN
1993-1994_Chelsea_Blackburn                           NaN              NaN
1993-1994_Liverpool_Sheffield Weds                    NaN              NaN
1993-1994_Man City_Leeds                              NaN              NaN

                                    AwayTeamCorners  HomeTeamFouls  \
MatchID
1993-1994_Arsenal_Coventry                      NaN            NaN
1993-1994_Aston Villa_QPR                       NaN            NaN
1993-1994_Chelsea_Blackburn                     NaN            NaN
1993-1994_Liverpool_Sheffield Weds              NaN            NaN
1993-1994_Man City_Leeds                        NaN            NaN

                                    AwayTeamFouls  HomeTeamYellowCards  \
MatchID
1993-1994_Arsenal_Coventry                    NaN                  NaN
1993-1994_Aston Villa_QPR                     NaN                  NaN
1993-1994_Chelsea_Blackburn                   NaN                  NaN
1993-1994_Liverpool_Sheffield Weds            NaN                  NaN
1993-1994_Man City_Leeds                      NaN                  NaN

                                    AwayTeamYellowCards  HomeTeamRedCards  \
MatchID
1993-1994_Arsenal_Coventry                          NaN               NaN
1993-1994_Aston Villa_QPR                           NaN               NaN
1993-1994_Chelsea_Blackburn                         NaN               NaN
1993-1994_Liverpool_Sheffield Weds                  NaN               NaN
1993-1994_Man City_Leeds                            NaN               NaN

                                    AwayTeamRedCards  B365HomeTeam  B365Draw  \
MatchID
1993-1994_Arsenal_Coventry                       NaN           NaN       NaN
1993-1994_Aston Villa_QPR                        NaN           NaN       NaN
1993-1994_Chelsea_Blackburn                      NaN           NaN       NaN
1993-1994_Liverpool_Sheffield Weds               NaN           NaN       NaN
1993-1994_Man City_Leeds                         NaN           NaN       NaN

                                    B365AwayTeam  B365Over2.5Goals  \
MatchID
1993-1994_Arsenal_Coventry                   NaN               NaN
1993-1994_Aston Villa_QPR                    NaN               NaN
1993-1994_Chelsea_Blackburn                  NaN               NaN
1993-1994_Liverpool_Sheffield Weds           NaN               NaN
1993-1994_Man City_Leeds                     NaN               NaN

                                    B365Under2.5Goals  MarketMaxHomeTeam  \
MatchID
1993-1994_Arsenal_Coventry                        NaN                NaN
1993-1994_Aston Villa_QPR                         NaN                NaN
1993-1994_Chelsea_Blackburn                       NaN                NaN
1993-1994_Liverpool_Sheffield Weds                NaN                NaN
1993-1994_Man City_Leeds                          NaN                NaN

                                    MarketMaxDraw  MarketMaxAwayTeam  \
MatchID
1993-1994_Arsenal_Coventry                    NaN                NaN
1993-1994_Aston Villa_QPR                     NaN                NaN
1993-1994_Chelsea_Blackburn                   NaN                NaN
1993-1994_Liverpool_Sheffield Weds            NaN                NaN
1993-1994_Man City_Leeds                      NaN                NaN

                                    MarketAvgHomeTeam  MarketAvgDraw  \
MatchID
1993-1994_Arsenal_Coventry                        NaN            NaN
1993-1994_Aston Villa_QPR                         NaN            NaN
1993-1994_Chelsea_Blackburn                       NaN            NaN
1993-1994_Liverpool_Sheffield Weds                NaN            NaN
1993-1994_Man City_Leeds                          NaN            NaN

                                    MarketAvgAwayTeam  MarketMaxOver2.5Goals  \
MatchID
1993-1994_Arsenal_Coventry                        NaN                    NaN
1993-1994_Aston Villa_QPR                         NaN                    NaN
1993-1994_Chelsea_Blackburn                       NaN                    NaN
1993-1994_Liverpool_Sheffield Weds                NaN                    NaN
1993-1994_Man City_Leeds                          NaN                    NaN

                                    MarketMaxUnder2.5Goals  \
MatchID
1993-1994_Arsenal_Coventry                             NaN
1993-1994_Aston Villa_QPR                              NaN
1993-1994_Chelsea_Blackburn                            NaN
1993-1994_Liverpool_Sheffield Weds                     NaN
1993-1994_Man City_Leeds                               NaN

                                    MarketAvgOver2.5Goals  \
MatchID
1993-1994_Arsenal_Coventry                            NaN
1993-1994_Aston Villa_QPR                             NaN
1993-1994_Chelsea_Blackburn                           NaN
1993-1994_Liverpool_Sheffield Weds                    NaN
1993-1994_Man City_Leeds                              NaN

                                    MarketAvgUnder2.5Goals  HomeTeamPoints  \
MatchID
1993-1994_Arsenal_Coventry                             NaN               0
1993-1994_Aston Villa_QPR                              NaN               3
1993-1994_Chelsea_Blackburn                            NaN               0
1993-1994_Liverpool_Sheffield Weds                     NaN               3
1993-1994_Man City_Leeds                               NaN               1

                                    AwayTeamPoints
MatchID
1993-1994_Arsenal_Coventry                       3
1993-1994_Aston Villa_QPR                        0
1993-1994_Chelsea_Blackburn                      3
1993-1994_Liverpool_Sheffield Weds               0
1993-1994_Man City_Leeds                         1

,MatchID,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,HalfTimeAwayTeamGoals,HalfTimeResult,Referee,HomeTeamShots,AwayTeamShots,HomeTeamShotsOnTarget,AwayTeamShotsOnTarget,HomeTeamCorners,AwayTeamCorners,HomeTeamFouls,AwayTeamFouls,HomeTeamYellowCards,AwayTeamYellowCards,HomeTeamRedCards,AwayTeamRedCards,B365HomeTeam,B365Draw,B365AwayTeam,B365Over2.5Goals,B365Under2.5Goals,MarketMaxHomeTeam,MarketMaxDraw,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
0,1993-1994_Arsenal_Coventry,1993-1994,1,1993-08-14,NaN,Arsenal,Coventry,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994_Aston Villa_QPR,1993-1994,1,1993-08-14,NaN,Aston Villa,QPR,4,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994_Chelsea_Blackburn,1993-1994,1,1993-08-14,NaN,Chelsea,Blackburn,1,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994_Liverpool_Sheffield Weds,1993-1994,1,1993-08-14,NaN,Liverpool,Sheffield Weds,2,0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994_Man City_Leeds,1993-1994,1,1993-08-14,NaN,Man City,Leeds,1,1,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [23]:
df.info()#getting information for columns with their data types and non-null value counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12160 entries, 0 to 12159
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MatchID                 12160 non-null  object
 1   Season                  12160 non-null  object
 2   MatchWeek               12160 non-null  int64
 3   Date                    12160 non-null  object
 4   Time                    2280 non-null   object
 5   HomeTeam                12160 non-null  object
 6   AwayTeam                12160 non-null  object
 7   FullTimeHomeTeamGoals   12160 non-null  int64
 8   FullTimeAwayTeamGoals   12160 non-null  int64
 9   FullTimeResult          12160 non-null  object
 10  HalfTimeHomeTeamGoals   11400 non-null  float64
 11  HalfTimeAwayTeamGoals   11400 non-null  float64
 12  HalfTimeResult          11400 non-null  object
 13  Referee                 9500 non-null   object
 14  HomeTeamShots           9500 non-null   float64
 15  AwayTeamShots           9500 non-null   float64
 16  HomeTeamShotsOnTarget   9500 non-null   float64
 17  AwayTeamShotsOnTarget   9500 non-null   float64
 18  HomeTeamCorners         9500 non-null   float64
 19  AwayTeamCorners         9500 non-null   float64
 20  HomeTeamFouls           9500 non-null   float64
 21  AwayTeamFouls           9500 non-null   float64
 22  HomeTeamYellowCards     9500 non-null   float64
 23  AwayTeamYellowCards     9500 non-null   float64
 24  HomeTeamRedCards        9500 non-null   float64
 25  AwayTeamRedCards        9500 non-null   float64
 26  B365HomeTeam            8740 non-null   float64
 27  B365Draw                8740 non-null   float64
 28  B365AwayTeam            8740 non-null   float64
 29  B365Over2.5Goals        3283 non-null   float64
 30  B365Under2.5Goals       3283 non-null   float64
 31  MarketMaxHomeTeam       2280 non-null   float64
 32  MarketMaxDraw           2280 non-null   float64
 33  MarketMaxAwayTeam       2280 non-null   float64
 34  MarketAvgHomeTeam       2280 non-null   float64
 35  MarketAvgDraw           2280 non-null   float64
 36  MarketAvgAwayTeam       2280 non-null   float64
 37  MarketMaxOver2.5Goals   2280 non-null   float64
 38  MarketMaxUnder2.5Goals  2280 non-null   float64
 39  MarketAvgOver2.5Goals   2280 non-null   float64
 40  MarketAvgUnder2.5Goals  2280 non-null   float64
 41  HomeTeamPoints          12160 non-null  int64
 42  AwayTeamPoints          12160 non-null  int64
dtypes: float64(29), int64(5), object(9)
memory usage: 4.0+ MB

In [24]:
df.drop(df.columns[26:41], axis=1, inplace=True) #dropping unnecessary columns
df.drop(columns=['MatchID','MatchWeek','Referee','Time'],inplace=True)
df.info() #checking the remained columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12160 entries, 0 to 12159
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Season                 12160 non-null  object
 1   Date                   12160 non-null  object
 2   HomeTeam               12160 non-null  object
 3   AwayTeam               12160 non-null  object
 4   FullTimeHomeTeamGoals  12160 non-null  int64
 5   FullTimeAwayTeamGoals  12160 non-null  int64
 6   FullTimeResult         12160 non-null  object
 7   HalfTimeHomeTeamGoals  11400 non-null  float64
 8   HalfTimeAwayTeamGoals  11400 non-null  float64
 9   HalfTimeResult         11400 non-null  object
 10  HomeTeamShots          9500 non-null   float64
 11  AwayTeamShots          9500 non-null   float64
 12  HomeTeamShotsOnTarget  9500 non-null   float64
 13  AwayTeamShotsOnTarget  9500 non-null   float64
 14  HomeTeamCorners        9500 non-null   float64
 15  AwayTeamCorners        9500 non-null   float64
 16  HomeTeamFouls          9500 non-null   float64
 17  AwayTeamFouls          9500 non-null   float64
 18  HomeTeamYellowCards    9500 non-null   float64
 19  AwayTeamYellowCards    9500 non-null   float64
 20  HomeTeamRedCards       9500 non-null   float64
 21  AwayTeamRedCards       9500 non-null   float64
 22  HomeTeamPoints         12160 non-null  int64
 23  AwayTeamPoints         12160 non-null  int64
dtypes: float64(14), int64(4), object(6)
memory usage: 2.2+ MB

In [25]:
df.head() #observing updated tabular data

,Season,Date,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,HalfTimeAwayTeamGoals,HalfTimeResult,HomeTeamShots,AwayTeamShots,HomeTeamShotsOnTarget,AwayTeamShotsOnTarget,HomeTeamCorners,AwayTeamCorners,HomeTeamFouls,AwayTeamFouls,HomeTeamYellowCards,AwayTeamYellowCards,HomeTeamRedCards,AwayTeamRedCards,HomeTeamPoints,AwayTeamPoints
0,1993-1994,1993-08-14,Arsenal,Coventry,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994,1993-08-14,Aston Villa,QPR,4,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994,1993-08-14,Chelsea,Blackburn,1,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994,1993-08-14,Liverpool,Sheffield Weds,2,0,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994,1993-08-14,Man City,Leeds,1,1,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [26]:
df = df[df['Season'] >= '2020-2021'].copy() #choosing the seasons between 2020-2021 and 2024-2025
df.head()

,Season,Date,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,HalfTimeAwayTeamGoals,HalfTimeResult,HomeTeamShots,AwayTeamShots,HomeTeamShotsOnTarget,AwayTeamShotsOnTarget,HomeTeamCorners,AwayTeamCorners,HomeTeamFouls,AwayTeamFouls,HomeTeamYellowCards,AwayTeamYellowCards,HomeTeamRedCards,AwayTeamRedCards,HomeTeamPoints,AwayTeamPoints
10260,2020-2021,2020-09-12,Fulham,Arsenal,0,3,A,0.0,1.0,A,5.0,13.0,2.0,6.0,2.0,3.0,12.0,12.0,2.0,2.0,0.0,0.0,0,3
10261,2020-2021,2020-09-12,Crystal Palace,Southampton,1,0,H,1.0,0.0,H,5.0,9.0,3.0,5.0,7.0,3.0,14.0,11.0,2.0,1.0,0.0,0.0,3,0
10262,2020-2021,2020-09-12,Liverpool,Leeds,4,3,H,3.0,2.0,H,22.0,6.0,6.0,3.0,9.0,0.0,9.0,6.0,1.0,0.0,0.0,0.0,3,0
10263,2020-2021,2020-09-12,West Ham,Newcastle,0,2,A,0.0,0.0,D,15.0,15.0,3.0,2.0,8.0,7.0,13.0,7.0,2.0,2.0,0.0,0.0,0,3
10264,2020-2021,2020-09-13,West Brom,Leicester,0,3,A,0.0,0.0,D,7.0,13.0,1.0,7.0,2.0,5.0,12.0,9.0,1.0,1.0,0.0,0.0,0,3

In [27]:
df.isnull().sum() #checking whether there are null values

Season                   0
Date                     0
HomeTeam                 0
AwayTeam                 0
FullTimeHomeTeamGoals    0
FullTimeAwayTeamGoals    0
FullTimeResult           0
HalfTimeHomeTeamGoals    0
HalfTimeAwayTeamGoals    0
HalfTimeResult           0
HomeTeamShots            0
AwayTeamShots            0
HomeTeamShotsOnTarget    0
AwayTeamShotsOnTarget    0
HomeTeamCorners          0
AwayTeamCorners          0
HomeTeamFouls            0
AwayTeamFouls            0
HomeTeamYellowCards      0
AwayTeamYellowCards      0
HomeTeamRedCards         0
AwayTeamRedCards         0
HomeTeamPoints           0
AwayTeamPoints           0
dtype: int64

In [28]:
#renaming columns into a proper name
df.rename(columns={'HomeTeam': 'home','AwayTeam': 'away','FullTimeHomeTeamGoals': 'home goals(full)','FullTimeAwayTeamGoals': 'away goals (full)','FullTimeResult': 'result(full)','HalfTimeHomeTeamGoals': 'home goals(half)','HalfTimeAwayTeamGoals': 'away goals(half)','HalfTimeResult': 'result(half)','HomeTeamShots': 'home shots','AwayTeamShots': 'away shots','HomeTeamShotsOnTarget': 'home shots on target','AwayTeamShotsOnTarget': 'away shots on target','HomeTeamCorners': 'home corners','AwayTeamCorners': 'away corners','HomeTeamFouls': 'home fouls','AwayTeamFouls': 'away fouls','HomeTeamYellowCards': 'home yellow cards','AwayTeamYellowCards': 'away yellow cards','HomeTeamRedCards': 'home red cards','AwayTeamRedCards': 'away red cards','HomeTeamPoints': 'home points','AwayTeamPoints': 'away points'},inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1900 entries, 10260 to 12159
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Season                1900 non-null   object
 1   Date                  1900 non-null   object
 2   home                  1900 non-null   object
 3   away                  1900 non-null   object
 4   home goals(full)      1900 non-null   int64
 5   away goals (full)     1900 non-null   int64
 6   result(full)          1900 non-null   object
 7   home goals(half)      1900 non-null   float64
 8   away goals(half)      1900 non-null   float64
 9   result(half)          1900 non-null   object
 10  home shots            1900 non-null   float64
 11  away shots            1900 non-null   float64
 12  home shots on target  1900 non-null   float64
 13  away shots on target  1900 non-null   float64
 14  home corners          1900 non-null   float64
 15  away corners          1900 non-null   float64
 16  home fouls            1900 non-null   float64
 17  away fouls            1900 non-null   float64
 18  home yellow cards     1900 non-null   float64
 19  away yellow cards     1900 non-null   float64
 20  home red cards        1900 non-null   float64
 21  away red cards        1900 non-null   float64
 22  home points           1900 non-null   int64
 23  away points           1900 non-null   int64
dtypes: float64(14), int64(4), object(6)
memory usage: 371.1+ KB

In [29]:
#changing spsecific columns' data types
df['home goals(half)']=df['home goals(half)'].astype(int)
df['away goals(half)']=df['away goals(half)'].astype(int)
df['home shots']=df['home shots'].astype(int)
df['away shots']=df['away shots'].astype(int)
df['home shots on target']=df['home shots on target'].astype(int)
df['away shots on target']=df['away shots on target'].astype(int)
df['home corners']=df['home corners'].astype(int)
df['away corners']=df['away corners'].astype(int)
df['home fouls']=df['home fouls'].astype(int)
df['away fouls']=df['away fouls'].astype(int)
df['away yellow cards']=df['away yellow cards'].astype(int)
df['home yellow cards']=df['home yellow cards'].astype(int)
df['away red cards']=df['away red cards'].astype(int)
df['home red cards']=df['home red cards'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1900 entries, 10260 to 12159
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Season                1900 non-null   object
 1   Date                  1900 non-null   object
 2   home                  1900 non-null   object
 3   away                  1900 non-null   object
 4   home goals(full)      1900 non-null   int64
 5   away goals (full)     1900 non-null   int64
 6   result(full)          1900 non-null   object
 7   home goals(half)      1900 non-null   int64
 8   away goals(half)      1900 non-null   int64
 9   result(half)          1900 non-null   object
 10  home shots            1900 non-null   int64
 11  away shots            1900 non-null   int64
 12  home shots on target  1900 non-null   int64
 13  away shots on target  1900 non-null   int64
 14  home corners          1900 non-null   int64
 15  away corners          1900 non-null   int64
 16  home fouls            1900 non-null   int64
 17  away fouls            1900 non-null   int64
 18  home yellow cards     1900 non-null   int64
 19  away yellow cards     1900 non-null   int64
 20  home red cards        1900 non-null   int64
 21  away red cards        1900 non-null   int64
 22  home points           1900 non-null   int64
 23  away points           1900 non-null   int64
dtypes: int64(18), object(6)
memory usage: 371.1+ KB

In [30]:

# fix the inconsistent column name
df = df.rename(columns={'away goals (full)': 'away goals(full)'})#fixing a naming mistake

# convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'])#changing Date column's data type into Date
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1900 entries, 10260 to 12159
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Season                1900 non-null   object
 1   Date                  1900 non-null   datetime64[ns]
 2   home                  1900 non-null   object
 3   away                  1900 non-null   object
 4   home goals(full)      1900 non-null   int64
 5   away goals(full)      1900 non-null   int64
 6   result(full)          1900 non-null   object
 7   home goals(half)      1900 non-null   int64
 8   away goals(half)      1900 non-null   int64
 9   result(half)          1900 non-null   object
 10  home shots            1900 non-null   int64
 11  away shots            1900 non-null   int64
 12  home shots on target  1900 non-null   int64
 13  away shots on target  1900 non-null   int64
 14  home corners          1900 non-null   int64
 15  away corners          1900 non-null   int64
 16  home fouls            1900 non-null   int64
 17  away fouls            1900 non-null   int64
 18  home yellow cards     1900 non-null   int64
 19  away yellow cards     1900 non-null   int64
 20  home red cards        1900 non-null   int64
 21  away red cards        1900 non-null   int64
 22  home points           1900 non-null   int64
 23  away points           1900 non-null   int64
dtypes: datetime64[ns](1), int64(18), object(5)
memory usage: 371.1+ KB

,Season,Date,home,away,home goals(full),away goals(full),result(full),home goals(half),away goals(half),result(half),home shots,away shots,home shots on target,away shots on target,home corners,away corners,home fouls,away fouls,home yellow cards,away yellow cards,home red cards,away red cards,home points,away points
10260,2020-2021,2020-09-12,Fulham,Arsenal,0,3,A,0,1,A,5,13,2,6,2,3,12,12,2,2,0,0,0,3
10261,2020-2021,2020-09-12,Crystal Palace,Southampton,1,0,H,1,0,H,5,9,3,5,7,3,14,11,2,1,0,0,3,0
10262,2020-2021,2020-09-12,Liverpool,Leeds,4,3,H,3,2,H,22,6,6,3,9,0,9,6,1,0,0,0,3,0
10263,2020-2021,2020-09-12,West Ham,Newcastle,0,2,A,0,0,D,15,15,3,2,8,7,13,7,2,2,0,0,0,3
10264,2020-2021,2020-09-13,West Brom,Leicester,0,3,A,0,0,D,7,13,1,7,2,5,12,9,1,1,0,0,0,3

In [34]:
df.to_csv('EPL_4.csv',index=False) #saving the new dataset